### ISSUE TITLE
AppThemes Updater does not notify about a new theme or plugin version

### ISSUE THREAD

**Issue by Jomark** [AppThemes/Updater#16]
A customer reported that https://forums.appthemes.com/report-vantage-bugs/appthemes-updater-does-not-warn-104120/page-2/#post442615 AppThemes Updater does not notify about a new theme or plugin version;

> AppThemes Updater 1.4.1 does not warn about a new theme version of Vantage.
> 
> It does not recognize the new version even when forcing the check manually via "wp-admin -> settings -> AppThemes Updater -> Check for Latest Versions".

> And it's happening with all themes I have installed.
> Not only Vantage, but ClassiPress and HireBee.

As enumerated here https://github.com/AppThemes/Updater/issues/15 I have already checked the "appthemes-vantage"folder name,  used my AppThems API and still the same. No related entries on the error log either.

What could be the other reason for this?

Anyway, I will send the customer's login credentials via Slack.

**Comment by dikiyforester** [comment]
Hello @Jomark !

I've checked the customer site with the following tests:
1. Used my API key to check. I see updates for some plugins from the marketplace, but not the Vantage. Although it's available with my key on my site.
2. Installed ClassiPress theme version 4.2.2 - I see Update notification. Works as expected

I think it's related only to Vantage and working fine with other themes and plugins.

I think there might be two reasons:
1. Maybe user account has outdated subscription. This can be checked through the AppThemes customers dashboard. If the customer sees the Vantage v4.2.12 on their AppThemes dashboard https://my.appthemes.com/purchases/ - it's not the reason of issue.
2. There is a legacy Vantage version 3.0.9 installed in the themes/vantage folder. Maybe try to delete this folder can help to resole the issue. If it used on some site in Network, try to rename the "vantage" folder to something else (but this may not have effect).

Please check both options and let me know the results.

**Comment by andreuerj** [comment]
Hi dikiyforester,

Follow the answers:

Reason 1 - My subscription is valid. You can check that in my AppThemes account. I also regenerated the AppThemes key as requested by Jomark in an attempt to work and no success at all. I can see and download the Vantage version 4.2.**12**, Hirebee 1.4.**11**, ClassiPress 4.2.**3** and son on, but I want update it automatically since I'm a regular customer. It's happening the same issue with all themes in my account, not just Vantage. I had to update manually HireBee to check a fix that was released by AppThemes DEVs. So, I can provide only Vantage now for your investigation.

Reason 2 - There is only one site on the network using the new theme 4. The old one is installed just to let me change it in the future if I decide to, if the new one starts bothering me for any reason, that is not the case nowadays. Remember that since December it was updating and nothing has changed since then.

**Comment by dikiyforester** [comment]
@andreuerj I think the old version 3.0.9 installed in the `vantage` folder prevents from updating version 4.2.7 installed in the `appthemes-vantage` folder. I'll do the same test on my site and if I will be able to replicate the issue, this will be the reason for sure.

Note, that I've tested with ClassiPress and HireBee on your site and they shows updates just fine:
![image](https://user-images.githubusercontent.com/4242025/95579219-a8c2d600-0a4e-11eb-89bf-d28b68d4652a.png)

**Comment by dikiyforester** [comment]
No, I can not replicate the issue having the same folder names.
There is something else...

**Comment by andreuerj** [comment]
The new and old Vantage themes are not at the same directory exactly:
new -> /wp-content/themes/appthemes-vantage/
old  -> /wp-content/vantage/vantage/
       -> /wp-content/themes/vantage-child/

If you need, I can rename the old Vantage theme folders.
I deactivated the old one on the network, but still no warning about the new version.

HireBee was not updating on my other network install and I had to overwrite the theme files to have the new version.
But, I can see in your picture that you uploaded the HireBee theme here and it's warning about the new version.
I really don't understand why it didn't warned me on the other install.
Sorry, but I deleted the classipress because I didn't understand how it got there... But now, I guess was you.

**Comment by dikiyforester** [comment]
@andreuerj I will need FTP access for adding some debugging code on your site. You can use my email for sending details.

**Comment by dikiyforester** [comment]
Well, seems like theme in folder appthemes-vantage doesn't fetches "AppThemes ID" header from the styles.css file. I have no idea why.

I've installed Vantage 4.2.11 into the appthemes-vantage-4 folder and it shows update to 4.2.12 just fine.

This looks like a very specific issue. Maybe it is worth to switch to this folder?

![image](https://user-images.githubusercontent.com/4242025/95956607-fd33d000-0e17-11eb-9116-0e77de75a7c1.png)

**Comment by dikiyforester** [comment]
Well, when I updated theme in new `appthemes-vantage-4` folder it disappeared, but original `appthemes-vantage` get updated.

Then, I've changes version to 4.2.11 to test if it will catch updates, but no luck, as before.

**Comment by dikiyforester** [comment]
I've manually edited the code in the AppThemes Updater plugin, so now it catches updates for Vantage. Although I haven't found why this didn't work...

![image](https://user-images.githubusercontent.com/4242025/95959264-a92aea80-0e1b-11eb-901c-8931f933ddec.png)
